# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
# locale                   : "en-US"
title                    : "Bertoblog"
title_separator          : "-"
name                     : &name "Bertoblog"
description              : &description
  en : "Undergrad in Physics, quantum computing scientist aspirant, developer in daily life and lover of learning new languages"
  pt : "Estudante de física maluco"
  de : "Dummkopf Student"
url                      : https://bertolinocastro.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "bertolinocastro/bertolinocastro.github.io"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "enabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : 'bertolinocastrogithubio'
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
atom_feed:
  path                   : # blank (default) uses feed.xml
# staticman:
#   # allowedFields          : ['name', 'email', 'url', 'message', 'replying_to_uid']
#   allowedFields          : ['name', 'email', 'message', 'replying_to', 'mention']
#   branch                 : "master" # "master", "gh-pages"
#   commitMessage          : "Comment from {fields.name} on {options.slug}"
#   filename               : comment-{@timestamp}-{@id}
#   format                 : "yaml"
#   # moderation             : true
#   moderation             : false
#   path                   : "_data/comments/{options.slug}"
#   requiredFields         : ['name', 'email', 'message']
#   transforms:
#     email                : "md5"
#   generatedFields:
#     date:
#       type               : "date"
#       options:
#         format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
# staticman_url            : https://staticman-bertolinocastro-bot.herokuapp.com/v2/entry/bertolinocastro/bertolinocastro.github.io/master/comments
reCaptcha: # reCaptcha used along to prevent spam in cmoment features with the staticman heroku app
  siteKey                : 6Lc6obAZAAAAAEkW4S3moi8d59wKzL_wj9OvOuA0
  secret                 : nmH3CtOvCbgdvGs80Kp61mPGKOsdNECwOLlGcJIS7wI4VHChj+SlBtPLytu+yz0c8pq7dPlr1BjTITQ64LEhPAc3doFUk+gDEMK0ZD1tMjGyNc5Xbu6BUs5JdnE348WZlZQo6v7G1dMEjGk/bDlCFlXFVHD9hRvdgTr60mtQaw9dUihY9NZwTQAZPev/YCOL5hpuo8VWtUolASXy6rdeZCYPeJyr/wN6SPyaIz4/yI3VJ781maPrJwOFVaKU2CQubbAJaGKWwMBpsXCF4qMP251rvhLfBC6zp+Dszqf78mgQB7c0ftboD1ReNs0KKoE4Bh45LhRt7NlzS/GctkR30mgL3WkUbQuQsT/7xdcV9QH2//buQ5YtyhschwApdRRe94c7NXg++GXpT9iEUt31qrXDKaCaERjw2SUOnrKQ0T0fRgfdQo0VtTe7Q36f2BdbhQdURWxfM1irNWO+fVE/6VnChatH46sCi5yptDKYlzV6A6r+G3eDUteFRrG1Huw2MV5q1UdqVAmcGfJA/nGgivxM3rzZYa1h31tXCNoxAIzlXiJnNwxF7W60ffh8ABneGvFEPhMawmPg06BkX/eiRf6fhq3uKUAlFC2vwN+OTEVrYU4bM23IZ5iIO4nrS6tniuJzEAA9bVwJuWSFwmbJG6r4guGBNrn9nl+PqyehQXY=


# Polyglot related
languages: ['en','pt','de']
default_lang: 'en'
parallel_localization: true
lang_from_path: true
exclude_from_localization:
  - _pages/sitemap.xml
  - assets/css
  - assets/fonts
  - assets/js/plugins
  - assets/js/vendor
  - assets/js/_main.js
  - assets/js/collapse.js
  - assets/js/main.min.js
  - images
  - files
  - markdown_generator
  - other_repo_webcontent
  - talkmap
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - TODO

# SEO Related
google_site_verification : 'google4787a8f78512a353.html'
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : 'gravatar.jpg' # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : 'Person' # Person or Organization (defaults to Person)
  name                   : 'Gabriel Bertolino' # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - 'https://www.instagram.com/bertolinodecastro/'
    - 'https://www.instagram.com/bertolinolearnlanguages/'
    - 'https://www.youtube.com/channel/UC-RaQ7JyH2UTBBt_JT6FpXw'
    - 'https://orcid.org/0000-0003-4925-4311'
    - 'https://www.stackoverflow.com/users/6844637/bertolino'
    - 'https://github.com/bertolinocastro'
    - 'http://lattes.cnpq.br/2951828503240063'


# Analytics
analytics:
  provider               : "google-analytics" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-172634076-1"


# Site Author
author:
  name             : "Gabriel Bertolino"
  shortname        : "Bertolino"
  avatar           : "profile.png"
  gravatar         : "gravatar.jpg"
  bio:
    en             : "Undergrad in Physics, quantum computing scientist aspirant, developer in daily life and lover of learning new languages"
    pt             : "Bio em pt"
    de             : "Biographie auf Deutsch"
  location:
    en             : "Brazil"
    pt             : "Brasil"
    de             : "Brasilien"
  employer:
    en             : "Bahia Federal University"
    pt             : "Univ. Federal da Bahia" # "Universidade Federal da Bahia" -> it breaks in bio for medium layouts
    de             : "Bahia Bundesuniversität"
  pubmed           :
  googlescholar    :
  email            : "bertolinocastro@gmail.com"
  emailhash        : '2531cd29a890a51bb80de16617231bf9'
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "bertolinocastro"
  google_plus      :
  keybase          :
  instagram        : "bertolinodecastro"
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         :
  orcid            : "https://orcid.org/0000-0003-4925-4311"
  pinterest        :
  soundcloud       :
  stackoverflow    : 6844637/bertolino
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : "UC-RaQ7JyH2UTBBt_JT6FpXw"
  wikipedia        :
  lattes           : "http://lattes.cnpq.br/2951828503240063"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
  - assets/js/lang-switcher.js
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - TODO
  # pages created by academicpages, but which I do not see very useful for now
  - _pages/non-menu-page.md
  - _pages/archive-layout-with-content.md
  - _pages/collection-archive.html
  - _pages/markdown.md
  - _pages/page-archive.html
  - _pages/portfolio.html
  - _pages/talkmap.html
  - _pages/talks.html
  - _pages/teaching.html
  - talkmap
  - markdown_generator
  - _talks
  - _teaching
  - _portfolio
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Refer to: https://jekyllrb.com/docs/collections/
# ..and to: https://jekyllrb.com/docs/permalinks/#collections
# Collections
collections:
  development:
    output: true
    permalink: /:collection/:path/
  # teaching:
  #   output: true
  #   permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  # portfolio:
  #   output: true
  #   permalink: /:collection/:path/
  # talks:
  #   output: true
  #   permalink: /:collection/:path/

# Refer to: https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      language_switcher: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      language_switcher: true
  # _development
  - scope:
      path: ""
      type: development
    values:
      layout: single
      author_profile: true
      language_switcher: true
      share: true
      comments: true
  # # _teaching
  # - scope:
  #     path: ""
  #     type: teaching
  #   values:
  #     layout: single
  #     author_profile: true
  #     language_switcher: true
  #     share: true
  #     comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      language_switcher: true
      share: true
      comments: true
  # # _portfolio
  # - scope:
  #     path: ""
  #     type: portfolio
  #   values:
  #     layout: single
  #     author_profile: true
  #     language_switcher: true
  #     share: true
  #     comment: true
  # # _talks
  # - scope:
  #     path: ""
  #     type: talks
  #   values:
  #     layout: talk
  #     author_profile: true
  #     language_switcher: true
  #     share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Refer to: https://jekyllrb.com/docs/pagination/
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /posts/page:num/
timezone: America/Bahia # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-polyglot
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  # - jekyll-sitemap
  - jekyll-minifier
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-polyglot
  - jekyll-paginate
  # - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Refer to: https://jekyllrb.com/docs/posts/#tags-and-categories
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

jekyll-minifier:
  uglifier_args:
    harmony: true
  exclude:
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - CHANGELOG
    - Capfile
    - Gemfile
    - Gruntfile.js
    - LICENSE
    - README
    - Rakefile
    - assets/js/_main.js
    - assets/js/plugins
    - assets/js/vendor
    - config
    - gulpfile.js
    - log
    - node_modules
    - package.json
    - tmp
    - vendor
    - TODO

last-modified-at:
  date-format: '%Y-%m-%d'

github: [metadata]
